plugins {
    id 'com.android.application'
}

android {
    namespace 'com.codex.stopwatch'
    compileSdk 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId 'com.codex.stopwatch'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:24.4.0'
}
